import os

files = [
    "syscall/syscall_numbers.npk",
    "syscall/posix_constants.npk",
    "syscall/errno.npk",
    "syscall/syscall.npk",
    "math/math.npk",
    "mem/mmap.npk",
    "mem/memset.npk",
    "mem/memcpy.npk",
    "mem/memutil.npk",
    "mem/slab.npk",
    "str/strlen.npk",
    "str/strchr.npk",
    "str/strcmp.npk",
    "str/strcpy.npk",
    "str/strlcpy.npk",
    "str/strtok.npk",
    "str/strview.npk",
    "str/string.npk",
    "str/strconv.npk",
    "str/strbuf.npk",
    "str/strfmt.npk",
    "fs/path.npk",
    "time/time_types.npk",
    "time/clock.npk",
    "time/timeofday.npk",
    "time/sleep.npk",
    "proc/env.npk",
    "proc/proc.npk",
    "proc/signal.npk",
    "proc/wait.npk",
    "proc/exit.npk",
    "proc/fork.npk",
    "proc/exec.npk",
    "io/io.npk",
    "io/pipe.npk",
    "io/fcntl.npk",
    "io/dup.npk",
    "io/seek.npk",
    "io/read.npk",
    "io/write.npk",
    "io/open.npk",
    "io/printf.npk",
    "io/bio/stdfiles.npk",
    "io/bio/strerror.npk",
    "io/bio/file.npk",
    "io/bio/fstate.npk",
    "io/bio/fopen.npk",
    "io/bio/fseek.npk",
    "io/bio/fchar.npk",
    "io/bio/fstr.npk",
    "io/bio/fio.npk",
    "io/bio/fprintf.npk",
    "io/bio/fscanf.npk",
    "io/bio/tmpfile.npk",
    "io/bio/bio.npk"
]

with open("/home/randy/Workspace/REPOS/libn/src/all.npk", "w") as f:
    for file in files:
        f.write(f'use "{file}".*;\n')

print("Rewrote all.npk")
