sed -i 's/raw tmpfile_get_entropy/tmpfile_get_entropy/g' src/io/bio/*.npk
sed -i 's/raw fgetc/fgetc/g' src/io/bio/*.npk
sed -i 's/raw fputc/fputc/g' src/io/bio/*.npk
sed -i 's/raw bio_scan_getc/bio_scan_getc/g' src/io/bio/*.npk
sed -i 's/raw bio_scan_skip_ws/bio_scan_skip_ws/g' src/io/bio/*.npk
sed -i 's/raw bio_scan_str/bio_scan_str/g' src/io/bio/*.npk
sed -i 's/raw bio_scan_int/bio_scan_int/g' src/io/bio/*.npk
sed -i 's/raw strerror/strerror/g' src/io/bio/*.npk
sed -i 's/raw str_snprintf1/str_snprintf1/g' src/io/*.npk
sed -i 's/raw path_strlen/path_strlen/g' src/fs/*.npk
sed -i 's/raw slab_class_slots/slab_class_slots/g' src/mem/*.npk
sed -i 's/raw slab_class_for_size/slab_class_for_size/g' src/mem/*.npk
sed -i 's/raw slab_freelist_get/slab_freelist_get/g' src/mem/*.npk
sed -i 's/raw mem_memcmp/mem_memcmp/g' src/mem/*.npk src/str/*.npk
sed -i 's/raw replicate_byte/replicate_byte/g' src/mem/*.npk
sed -i 's/raw mem_memchr/mem_memchr/g' src/mem/*.npk src/str/*.npk
sed -i 's/raw page_align_up/page_align_up/g' src/mem/*.npk
sed -i 's/raw mem_malloc/mem_malloc/g' src/mem/*.npk
sed -i 's/raw mem_memrchr/mem_memrchr/g' src/str/*.npk
sed -i 's/raw mem_memmem/mem_memmem/g' src/str/*.npk
sed -i 's/raw strview_find_char/strview_find_char/g' src/str/*.npk
sed -i 's/raw strview_find_str/strview_find_str/g' src/str/*.npk
sed -i 's/raw strview_find/strview_find/g' src/str/*.npk
sed -i 's/raw strview_split_once_char/strview_split_once_char/g' src/str/*.npk
sed -i 's/raw strbuf_new_cap/strbuf_new_cap/g' src/str/*.npk
sed -i 's/raw fwrite/fwrite/g' src/str/*.npk
sed -i 's/raw str_strscpy/str_strscpy/g' src/str/*.npk
sed -i 's/raw str_strlcpy/str_strlcpy/g' src/str/*.npk
sed -i 's/raw math_sat_add_i64/math_sat_add_i64/g' src/math/*.npk
sed -i 's/raw math_abs_i64/math_abs_i64/g' src/math/*.npk
sed -i 's/raw math_div_floor_i64/math_div_floor_i64/g' src/math/*.npk
sed -i 's/raw math_clz/math_clz/g' src/math/*.npk
sed -i 's/raw math_log2_floor/math_log2_floor/g' src/math/*.npk
sed -i 's/raw math_isqrt/math_isqrt/g' src/math/*.npk
sed -i 's/raw math_gcd/math_gcd/g' src/math/*.npk
sed -i 's/raw math_ctz/math_ctz/g' src/math/*.npk
sed -i 's/raw math_sat_mul_i64/math_sat_mul_i64/g' src/math/*.npk
sed -i 's/raw sys1/sys1/g' src/syscall/*.npk
sed -i 's/raw getenv/getenv/g' src/proc/*.npk
